// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvailableHoursController from "./available_hours_controller"
application.register("available-hours", AvailableHoursController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CmrController from "./cmr_controller"
application.register("cmr", CmrController)
